version: '3.7'
services:
  server:
    image: stgleb/user-app
    entrypoint: ["/bin/user-app", "templatesDir", "/templates"]
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - database
  database:
    image: stgleb/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    network_mode: "host"
